// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RepositoryDescription repository description
//
// swagger:model RepositoryDescription
type RepositoryDescription struct {

	// The description of the repository.
	Description string `json:"description,omitempty"`
}

// Validate validates this repository description
func (m *RepositoryDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this repository description based on context it is used
func (m *RepositoryDescription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RepositoryDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RepositoryDescription) UnmarshalBinary(b []byte) error {
	var res RepositoryDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
