// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Tags tags
//
// swagger:model Tags
type Tags struct {

	// The repository's used tag.
	Tag string `json:"tag,omitempty"`
}

// Validate validates this tags
func (m *Tags) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tags based on context it is used
func (m *Tags) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Tags) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tags) UnmarshalBinary(b []byte) error {
	var res Tags
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
