// Code generated by go-swagger; DO NOT EDIT.

package legacy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// QuotaRefObject quota ref object
//
// swagger:model QuotaRefObject
type QuotaRefObject interface{}
