// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProjectsParams creates a new GetProjectsParams object
// with the default values initialized.
func NewGetProjectsParams() *GetProjectsParams {
	var ()
	return &GetProjectsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProjectsParamsWithTimeout creates a new GetProjectsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProjectsParamsWithTimeout(timeout time.Duration) *GetProjectsParams {
	var ()
	return &GetProjectsParams{

		timeout: timeout,
	}
}

// NewGetProjectsParamsWithContext creates a new GetProjectsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProjectsParamsWithContext(ctx context.Context) *GetProjectsParams {
	var ()
	return &GetProjectsParams{

		Context: ctx,
	}
}

// NewGetProjectsParamsWithHTTPClient creates a new GetProjectsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProjectsParamsWithHTTPClient(client *http.Client) *GetProjectsParams {
	var ()
	return &GetProjectsParams{
		HTTPClient: client,
	}
}

/*GetProjectsParams contains all the parameters to send to the API endpoint
for the get projects operation typically these are written to a http.Request
*/
type GetProjectsParams struct {

	/*Name
	  The name of project.

	*/
	Name *string
	/*Owner
	  The name of project owner.

	*/
	Owner *string
	/*Page
	  The page number, default is 1.

	*/
	Page *int32
	/*PageSize
	  The size of per page, default is 10, maximum is 100.

	*/
	PageSize *int32
	/*Public
	  The project is public or private.

	*/
	Public *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get projects params
func (o *GetProjectsParams) WithTimeout(timeout time.Duration) *GetProjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get projects params
func (o *GetProjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get projects params
func (o *GetProjectsParams) WithContext(ctx context.Context) *GetProjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get projects params
func (o *GetProjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get projects params
func (o *GetProjectsParams) WithHTTPClient(client *http.Client) *GetProjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get projects params
func (o *GetProjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get projects params
func (o *GetProjectsParams) WithName(name *string) *GetProjectsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get projects params
func (o *GetProjectsParams) SetName(name *string) {
	o.Name = name
}

// WithOwner adds the owner to the get projects params
func (o *GetProjectsParams) WithOwner(owner *string) *GetProjectsParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get projects params
func (o *GetProjectsParams) SetOwner(owner *string) {
	o.Owner = owner
}

// WithPage adds the page to the get projects params
func (o *GetProjectsParams) WithPage(page *int32) *GetProjectsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get projects params
func (o *GetProjectsParams) SetPage(page *int32) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get projects params
func (o *GetProjectsParams) WithPageSize(pageSize *int32) *GetProjectsParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get projects params
func (o *GetProjectsParams) SetPageSize(pageSize *int32) {
	o.PageSize = pageSize
}

// WithPublic adds the public to the get projects params
func (o *GetProjectsParams) WithPublic(public *bool) *GetProjectsParams {
	o.SetPublic(public)
	return o
}

// SetPublic adds the public to the get projects params
func (o *GetProjectsParams) SetPublic(public *bool) {
	o.Public = public
}

// WriteToRequest writes these params to a swagger request
func (o *GetProjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Owner != nil {

		// query param owner
		var qrOwner string
		if o.Owner != nil {
			qrOwner = *o.Owner
		}
		qOwner := qrOwner
		if qOwner != "" {
			if err := r.SetQueryParam("owner", qOwner); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int32
		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt32(qrPageSize)
		if qPageSize != "" {
			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}

	}

	if o.Public != nil {

		// query param public
		var qrPublic bool
		if o.Public != nil {
			qrPublic = *o.Public
		}
		qPublic := swag.FormatBool(qrPublic)
		if qPublic != "" {
			if err := r.SetQueryParam("public", qPublic); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
