// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetReplicationExecutionsIDTasksParams creates a new GetReplicationExecutionsIDTasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetReplicationExecutionsIDTasksParams() *GetReplicationExecutionsIDTasksParams {
	return &GetReplicationExecutionsIDTasksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetReplicationExecutionsIDTasksParamsWithTimeout creates a new GetReplicationExecutionsIDTasksParams object
// with the ability to set a timeout on a request.
func NewGetReplicationExecutionsIDTasksParamsWithTimeout(timeout time.Duration) *GetReplicationExecutionsIDTasksParams {
	return &GetReplicationExecutionsIDTasksParams{
		timeout: timeout,
	}
}

// NewGetReplicationExecutionsIDTasksParamsWithContext creates a new GetReplicationExecutionsIDTasksParams object
// with the ability to set a context for a request.
func NewGetReplicationExecutionsIDTasksParamsWithContext(ctx context.Context) *GetReplicationExecutionsIDTasksParams {
	return &GetReplicationExecutionsIDTasksParams{
		Context: ctx,
	}
}

// NewGetReplicationExecutionsIDTasksParamsWithHTTPClient creates a new GetReplicationExecutionsIDTasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetReplicationExecutionsIDTasksParamsWithHTTPClient(client *http.Client) *GetReplicationExecutionsIDTasksParams {
	return &GetReplicationExecutionsIDTasksParams{
		HTTPClient: client,
	}
}

/* GetReplicationExecutionsIDTasksParams contains all the parameters to send to the API endpoint
   for the get replication executions ID tasks operation.

   Typically these are written to a http.Request.
*/
type GetReplicationExecutionsIDTasksParams struct {

	/* ID.

	   The execution ID.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get replication executions ID tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReplicationExecutionsIDTasksParams) WithDefaults() *GetReplicationExecutionsIDTasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get replication executions ID tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetReplicationExecutionsIDTasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) WithTimeout(timeout time.Duration) *GetReplicationExecutionsIDTasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) WithContext(ctx context.Context) *GetReplicationExecutionsIDTasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) WithHTTPClient(client *http.Client) *GetReplicationExecutionsIDTasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) WithID(id int64) *GetReplicationExecutionsIDTasksParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get replication executions ID tasks params
func (o *GetReplicationExecutionsIDTasksParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetReplicationExecutionsIDTasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
