// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewPostRetentionsIDExecutionsParams creates a new PostRetentionsIDExecutionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostRetentionsIDExecutionsParams() *PostRetentionsIDExecutionsParams {
	return &PostRetentionsIDExecutionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostRetentionsIDExecutionsParamsWithTimeout creates a new PostRetentionsIDExecutionsParams object
// with the ability to set a timeout on a request.
func NewPostRetentionsIDExecutionsParamsWithTimeout(timeout time.Duration) *PostRetentionsIDExecutionsParams {
	return &PostRetentionsIDExecutionsParams{
		timeout: timeout,
	}
}

// NewPostRetentionsIDExecutionsParamsWithContext creates a new PostRetentionsIDExecutionsParams object
// with the ability to set a context for a request.
func NewPostRetentionsIDExecutionsParamsWithContext(ctx context.Context) *PostRetentionsIDExecutionsParams {
	return &PostRetentionsIDExecutionsParams{
		Context: ctx,
	}
}

// NewPostRetentionsIDExecutionsParamsWithHTTPClient creates a new PostRetentionsIDExecutionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostRetentionsIDExecutionsParamsWithHTTPClient(client *http.Client) *PostRetentionsIDExecutionsParams {
	return &PostRetentionsIDExecutionsParams{
		HTTPClient: client,
	}
}

/* PostRetentionsIDExecutionsParams contains all the parameters to send to the API endpoint
   for the post retentions ID executions operation.

   Typically these are written to a http.Request.
*/
type PostRetentionsIDExecutionsParams struct {

	// Action.
	Action PostRetentionsIDExecutionsBody

	/* ID.

	   Retention ID.

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post retentions ID executions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRetentionsIDExecutionsParams) WithDefaults() *PostRetentionsIDExecutionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post retentions ID executions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostRetentionsIDExecutionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) WithTimeout(timeout time.Duration) *PostRetentionsIDExecutionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) WithContext(ctx context.Context) *PostRetentionsIDExecutionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) WithHTTPClient(client *http.Client) *PostRetentionsIDExecutionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAction adds the action to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) WithAction(action PostRetentionsIDExecutionsBody) *PostRetentionsIDExecutionsParams {
	o.SetAction(action)
	return o
}

// SetAction adds the action to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) SetAction(action PostRetentionsIDExecutionsBody) {
	o.Action = action
}

// WithID adds the id to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) WithID(id int64) *PostRetentionsIDExecutionsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post retentions ID executions params
func (o *PostRetentionsIDExecutionsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostRetentionsIDExecutionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Action); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
