name: Go Test

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Hack Code Climate and Go Modules
        if: github.event_name != 'pull_request'
        run: mkdir -p github.com/testwill && ln -sf $(pwd) github.com/testwill/goharbor-client

      - name: Test & publish code coverage
        if: github.event_name != 'pull_request'
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.codeClimateReporterID }}
        with:
          coverageCommand: go test -coverprofile=c.out ./...
          debug: true
          prefix: 'github.com/${{ github.repository }}/v5'

      - name: Go Test
        if: github.event_name == 'pull_request'
        run: go test -coverprofile=c.out ./...