name: Verify code generation integrity

on: pull_request

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15.1
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run swagger code generation
        run: make swagger-generate

      - name: Run mockery code generation
        run: make mock-generate

      - name: Test diff
        run: |
          git diff | cat
          git status --porcelain=v1
          test $(git status --porcelain=v1 | wc -l) -eq 0
