name: Verify

on: pull_request

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Set up Swagger
        run: apt -y install gnupg ca-certificates && \
          apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61 && \
          echo "deb https://dl.bintray.com/go-swagger/goswagger-debian ubuntu main" | tee /etc/apt/sources.list.d/goswagger.list && \
          apt -y update && \
          apt -y install swagger

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run code generation
        run: make swagger

      - name: Test diff
        run: |
          git diff | cat
          git status --porcelain=v1
          test $(git status --porcelain=v1 | wc -l) -eq 0